name: Deploy to S3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_S3_BUCKET_PROD: ${{ secrets.AWS_S3_BUCKET_PROD }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: E3DKH438IVMXVO
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Sync non-HTML assets with long cache
      - name: Sync non-HTML files to S3 bucket (long cache)
        run: |
          aws s3 sync ${SOURCE_DIR:-.} s3://${AWS_S3_BUCKET_PROD}/ \
            --no-progress --delete \
            --cache-control "max-age=31536000,public" \
            --exclude "*.html" \
            --no-paginate

      # Sync HTML files with short cache
      - name: Sync HTML files to S3 bucket (short cache)
        run: |
          aws s3 sync ${SOURCE_DIR:-.} s3://${AWS_S3_BUCKET_PROD}/ \
            --no-progress --delete \
            --cache-control "max-age=60,public" \
            --include "*.html" \
            --no-paginate

      - name: Set deployment timestamp
        id: deployment-timestamp
        run: |
          echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Invalidate CloudFront cache
        run: |
          if [ -n "$AWS_CLOUDFRONT_DISTRIBUTION_ID" ]; then
            aws cloudfront create-invalidation \
              --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"
          fi

      - name: Verify deployment
        run: |
          ENDPOINT="https://d2mw4d8injvp1v.cloudfront.net"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT)
          if [[ $HTTP_STATUS == 2* ]]; then
            echo "✅ Deployment verified successfully ($HTTP_STATUS)"
          else
            echo "❌ Deployment verification failed: HTTP Status $HTTP_STATUS"
            exit 1
          fi

      - name: Deployment summary
        run: |
          echo "🚀 Deployed to production at ${{ steps.deployment-timestamp.outputs.timestamp }}"
          echo "📦 Build artifacts successfully uploaded to S3"
          echo "🔄 CloudFront cache invalidated"